packages:
  - "apps/*"
  - "packages/*"

catalog:
  typescript: ^5.7.3
  zod: ^3.24.2
  clsx: ^2.1.1

catalogs:
  ui:
    lucide-react: ^0.475.0
    next: ^15.2.3
    next-themes: ^0.4.4
    react: ^19.0.0
    react-dom: ^19.0.0
  tailwind4:
    tailwindcss: ^4.0.8
    tailwind-merge: ^3.0.1
    tw-animate-css: ^1.2.4
